version: '3'
services:
  pymc3:
    container_name: pymc3
    image: pymc3
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - "./:/root/ab_testing"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.notebook_dir='/root/ab_testing' --NotebookApp.token=''
    ports:
      - 8888:8888
